name: ncpa
version: '2.4.1'
summary: Nagios Cross-Platform Agent
description: |
  NCPA (Nagios Cross-Platform Agent) is an open-source monitoring agent that provides performance metrics, system data, and remote access capabilities to Nagios XI, Nagios Core, and other monitoring solutions.

grade: stable
confinement: strict

parts:
  ncpa:
    source: https://github.com/NagiosEnterprises/ncpa/archive/v2.4.1.tar.gz
    plugin: python
    python-version: python3
    stage-packages:
      - python3-pip
    after:
      - python3
    override-build: |
      snapcraftctl build
      pip3 install -r $SNAPCRAFT_PART_BUILD/requirements.txt -t $SNAPCRAFT_PART_INSTALL
