name: ncpa
version: '2.4.1'
summary: Nagios Cross-Platform Agent
description: |
  NCPA (Nagios Cross-Platform Agent) is an open-source monitoring agent that provides performance metrics, system data, and remote access capabilities to Nagios XI, Nagios Core, and other monitoring solutions.

grade: stable
confinement: strict
base: core20

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

parts:
  ncpa:
    source: https://github.com/NagiosEnterprises/ncpa/archive/v2.4.1.tar.gz
    plugin: python
    python-version: python3
    stage-packages:
      - python3-pip
    after:
      - python3
    override-build: |
      snapcraftctl build
      pip3 install -r $SNAPCRAFT_PART_BUILD/requirements.txt -t $SNAPCRAFT_PART_INSTALL

apps:
  ncpa-server:
    command: bin/ncpa_passive.py --config $SNAP_DATA/etc/ncpa.cfg
    daemon: simple
    restart-condition: on-failure
    plugs:
      - network
      - network-bind
      - process-control

  ncpa-config:
    command: bin/ncpa-config --config $SNAP_DATA/etc/ncpa.cfg
    plugs:
      - network

  ncpa-listen:
    command: bin/ncpa-passive-listen --config $SNAP_DATA/etc/ncpa.cfg
    plugs:
      - network
      - network-bind

  ncpa-plugins:
    command: bin/ncpa-plugins --config $SNAP_DATA/etc/ncpa.cfg
    plugs:
      - network